- id: '1646609164542'
  alias: Turn on lights in the evening
  description: ''
  triggers:
  - event: sunset
    offset: -00:60:00
    trigger: sun
  conditions:
  - condition: zone
    entity_id: person.jessie_puls
    zone: zone.home
  actions:
  - action: light.turn_on
    metadata: {}
    data: {}
    target:
      device_id: df4fa28466834af8b35ecaa3590c58ad
  - action: light.turn_on
    metadata: {}
    data: {}
    target:
      device_id: f0f1f52e88e8ec0ebc40600ce5594100
  mode: single
- id: '1646610339547'
  alias: Turn on Outdoor Lights in the Evening
  description: ''
  triggers:
  - event: sunset
    offset: '0'
    trigger: sun
  conditions: []
  actions:
  - data: {}
    target:
      area_id: outdoors
    action: light.turn_on
  - data: {}
    target:
      area_id: outdoors
    action: switch.turn_on
  mode: single
- id: '1646616822825'
  alias: Turn off Outdoor Lights At Night
  description: ''
  triggers:
  - at: '23:59:00'
    trigger: time
  conditions: []
  actions:
  - data: {}
    target:
      area_id: outdoors
    action: light.turn_off
  - data: {}
    target:
      area_id: outdoors
    action: switch.turn_off
  mode: single
- id: '1646634523203'
  alias: Bedtime
  description: ''
  triggers:
  - event_type: ''
    trigger: event
  conditions: []
  actions:
  - data: {}
    target:
      entity_id: media_player.upstairs_tv
    action: media_player.turn_off
  - type: turn_on
    device_id: ed25db0eec179417785a7a4ef51664bc
    entity_id: light.hallway_main_lights
    domain: light
    brightness_pct: 30
  - data: {}
    target:
      area_id:
      - kitchen
      - living_room
      - outdoors
      - dining_room
    action: light.turn_off
  - data: {}
    target:
      area_id:
      - outdoors
      - living_room
    action: switch.turn_off
  - data: {}
    action: script.turn_off_three_season_porch_heater
  mode: single
- id: '1698817689655'
  alias: Back Yard Lights
  description: ''
  use_blueprint:
    path: chrissalter/state-bonding-simplified-and-easier.yaml
    input:
      entity_list:
      - switch.exterior_string_lights
      - light.exterior_deck_lights
- id: '1704689880782'
  alias: Turn off indoor lights at night
  description: ''
  triggers:
  - at: 02:00:00
    trigger: time
  conditions: []
  actions:
  - type: turn_off
    device_id: 3dfe43c736d7de5ca73345ff4601890b
    entity_id: d27b1c7bba033a9ad231e1dcd6715d0f
    domain: light
  - type: turn_off
    device_id: 253efb31b1f2b0c67313571577004b52
    entity_id: 88fb2a2e11645baf189605b8ff1fea5e
    domain: light
  - type: turn_off
    device_id: e6f2916caa899a05821b4f79976ddca8
    entity_id: 1d5da9fb4629653b7e9d10bab973b1a7
    domain: light
  - type: turn_off
    device_id: 35450f7564a111b96830dcaf0fee042e
    entity_id: 281bcbe36515e2752c3d9f0741f1f9b9
    domain: light
  - action: light.turn_off
    metadata: {}
    data: {}
    target:
      device_id: f0f1f52e88e8ec0ebc40600ce5594100
  - action: light.turn_off
    metadata: {}
    data: {}
    target:
      device_id: df4fa28466834af8b35ecaa3590c58ad
  mode: single
- id: '1707782077065'
  alias: Dining Room Lights Sync
  description: ''
  use_blueprint:
    path: chrissalter/state-bonding-simplified-and-easier.yaml
    input:
      entity_list:
      - light.dining_room_ceiling_fan_light
      - light.hue_smart_plug_1
      - light.hue_smart_plug_1_2
- id: '1748154090198'
  alias: Chicken Coop Door Open
  description: ''
  triggers:
  - trigger: sun
    event: sunrise
    offset: 00:60:00
  - trigger: time
    at: 07:00:00
  conditions:
  - condition: or
    conditions:
    - condition: device
      device_id: e26628038ef92e9846da78982743feea
      domain: cover
      entity_id: 37429b3d46890887caf19f8ce4a0f3d6
      type: is_closing
    - condition: device
      device_id: e26628038ef92e9846da78982743feea
      domain: cover
      entity_id: 37429b3d46890887caf19f8ce4a0f3d6
      type: is_closed
  actions:
  - device_id: e26628038ef92e9846da78982743feea
    domain: cover
    entity_id: 37429b3d46890887caf19f8ce4a0f3d6
    type: open
  mode: single
- id: '1748275171272'
  alias: Chicken Coop Door Close
  description: ''
  triggers:
  - trigger: sun
    event: sunset
    offset: 00:30:00
  - trigger: time
    at: '21:00:00'
  conditions:
  - condition: or
    conditions:
    - condition: device
      device_id: e26628038ef92e9846da78982743feea
      domain: cover
      entity_id: 37429b3d46890887caf19f8ce4a0f3d6
      type: is_open
    - condition: device
      device_id: e26628038ef92e9846da78982743feea
      domain: cover
      entity_id: 37429b3d46890887caf19f8ce4a0f3d6
      type: is_opening
  actions:
  - device_id: e26628038ef92e9846da78982743feea
    domain: cover
    entity_id: 37429b3d46890887caf19f8ce4a0f3d6
    type: close
  mode: single
  - type: turn_on
    device_id: 28f263e6d022818ac183308b530f7b35
    entity_id: cf7302fad5784a8fd74e8ab2bc8d44a9
    domain: light
  mode: single
- id: '1755720058681'
  alias: When I arrive home
  description: ''
  triggers:
  - trigger: zone
    entity_id: person.jessie_puls
    zone: zone.home
    event: enter
  conditions:
  - condition: sun
    after: sunset
    after_offset: -00:30:00
  actions:
  - action: light.turn_on
    metadata: {}
    data: {}
    target:
      device_id: df4fa28466834af8b35ecaa3590c58ad
  - action: light.turn_on
    metadata: {}
    data: {}
    target:
      device_id: f0f1f52e88e8ec0ebc40600ce5594100
  mode: single
- id: '1768495878924'
  alias: When I leave home
  description: ''
  triggers:
  - trigger: state
    entity_id:
    - person.jessie_puls
    from:
    - home
    to:
    - not_home
  conditions: []
  actions:
  - action: light.turn_off
    metadata: {}
    target:
      area_id:
      - living_room
      - kitchen
      - dining
      - stairs
      - hallway
      entity_id:
      - light.bedroom_lamp
      - light.three_season_porch
    data: {}
  mode: single
- id: '1771822848950'
  alias: Chicken Feeder Close at Sunset
  description: ''
  triggers:
  - trigger: sun
    event: sunset
    offset: 0
  conditions:
  - condition: state
    entity_id: cover.jessica_s_feeder_feeder
    state:
    - open
    - opening
  actions:
  - device_id: 5dca65a0ebb141eded4673411b355aab
    domain: cover
    entity_id: 5d96f91d0db6542a7b2dc5632c4dc71e
    type: close
  mode: single
- id: '1771822978368'
  alias: Chicken Feeder Open at Sunrise
  description: ''
  triggers:
  - trigger: sun
    event: sunrise
    offset: 0
  conditions:
  - condition: state
    entity_id: cover.jessica_s_feeder_feeder
    state:
    - closed
    - closing
  actions:
  - device_id: 5dca65a0ebb141eded4673411b355aab
    domain: cover
    entity_id: 5d96f91d0db6542a7b2dc5632c4dc71e
    type: open
  mode: single
