
# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Text to speech
tts:
  - platform: google_translate

sensor:
  - platform: time_date
    display_options:
      - 'time'
      - 'date'
      - 'date_time'
      - 'date_time_utc'
      - 'date_time_iso'
      - 'time_date'
      - 'time_utc'
      - 'beat'

# Need this because sonos speakers are on a differnt subnet from home assistant
sonos:
  media_player:
    hosts:
      - !secret sonos_livingroom_ip
      - !secret sonos_basement_ip
      - !secret sonos_portable_ip

alexa_media:
  accounts:
    - email: !secret amazon_user
      password: !secret amazon_password
      url: amazon.com
      include_devices:
        - "Three Season Porch"

spotify:
  client_id: !secret spotify_cient_id
  client_secret: !secret spotify_client_secret

nest:
  client_id: !secret nest_client_id
  client_secret: !secret nest_client_secret
  project_id: !secret nest_project_id

lovelace:
  mode: yaml
  resources:
    - type: module
      url: /hacsfiles/lovelace-card-mod/card-mod.js
    - type: module
      url: /hacsfiles/lovelace-layout-card/layout-card.js
    - type: module
      url: /hacsfiles/mini-graph-card/mini-graph-card-bundle.js
    - type: module
      url: /hacsfiles/mini-media-player/mini-media-player-bundle.js
    - type: module
      url: /hacsfiles/atomic-calendar-revive/atomic-calendar-revive.js
    - type: module
      url: /hacsfiles/weather-card/weather-card.js
    - type: module
      url: /hacsfiles/config-template-card/config-template-card.js
    - type: module
      url: /hacsfiles/button-card/button-card.js
    - type: module
      url: /hacsfiles/lovelace-state-switch/state-switch.js
    - type: module
      url: /hacsfiles/kiosk-mode/kiosk-mode.js
    - type: css
      url: /local/style.css
    - type: css
      url: /local/latofonts.css
  dashboards:
    lovelace-three-season-porch:
      mode: yaml
      icon: mdi:fireplace
      title: Three Season Porch
      filename: dashboards/three-season-porch.yaml
      show_in_sidebar: true
      require_admin: false
    lovelace-main-panel:
      mode: yaml
      icon: mdi:home
      title: Main Panel
      filename: dashboards/main-panel.yaml
      show_in_sidebar: true
      require_admin: false

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
light: !include lights.yaml
group: !include groups.yaml

